import type { ToolDef } from '../types.js';

const owner = { description: 'Repository owner' };
const repo = { description: 'Repository path name' };
const page = { description: 'Page number', type: 'number' as const };
const per_page = { description: 'Items per page (max 100)', type: 'number' as const };

export const activityTools: ToolDef[] = [
    {
        name: 'gitee_list_notifications',
        description: 'List notifications for the authenticated user',
        method: 'GET',
        path: '/notifications/threads',
        optional: {
            unread: { description: 'Only unread notifications', type: 'boolean' },
            participating: { description: 'Only participating notifications', type: 'boolean' },
            type: { description: 'Notification type filter', enum: ['AccountActivate', 'AssignedIssue', 'AssignedPullRequest', 'Comment', 'NewIssue', 'NewPullRequest', 'PullRequestMerged', 'UpdatedPullRequest'] },
            since: 'ISO 8601 date',
            before: 'ISO 8601 date',
            ids: 'Comma-separated notification IDs',
            page, per_page,
        },
    },
    {
        name: 'gitee_get_notification',
        description: 'Get a single notification thread',
        method: 'GET',
        path: '/notifications/threads/{id}',
        required: { id: 'Notification ID' },
    },
    {
        name: 'gitee_mark_notification_read',
        description: 'Mark a notification as read',
        method: 'PATCH',
        path: '/notifications/threads/{id}',
        required: { id: 'Notification ID' },
    },
    {
        name: 'gitee_mark_all_notifications_read',
        description: 'Mark all notifications as read',
        method: 'PUT',
        path: '/notifications/threads',
        optional: { ids: 'Comma-separated notification IDs to mark (empty = all)' },
    },
    {
        name: 'gitee_get_notification_count',
        description: 'Get unread notification count',
        method: 'GET',
        path: '/notifications/count',
        optional: { unread: { description: 'Count only unread', type: 'boolean' } },
    },
    {
        name: 'gitee_list_repo_notifications',
        description: 'List notifications for a repository',
        method: 'GET',
        path: '/repos/{owner}/{repo}/notifications',
        required: { owner, repo },
        optional: { unread: { description: 'Only unread', type: 'boolean' }, participating: { description: 'Only participating', type: 'boolean' }, since: 'ISO 8601 date', before: 'ISO 8601 date', page, per_page },
    },
    {
        name: 'gitee_mark_repo_notifications_read',
        description: 'Mark all notifications in a repository as read',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/notifications',
        required: { owner, repo },
    },
    {
        name: 'gitee_list_messages',
        description: 'List private messages',
        method: 'GET',
        path: '/notifications/messages',
        optional: { unread: { description: 'Only unread', type: 'boolean' }, page, per_page },
    },
    {
        name: 'gitee_get_message',
        description: 'Get a private message',
        method: 'GET',
        path: '/notifications/messages/{id}',
        required: { id: 'Message ID' },
    },
    {
        name: 'gitee_send_message',
        description: 'Send a private message',
        method: 'POST',
        path: '/notifications/messages',
        required: { username: 'Recipient username', content: 'Message content' },
    },
    {
        name: 'gitee_mark_message_read',
        description: 'Mark a private message as read',
        method: 'PATCH',
        path: '/notifications/messages/{id}',
        required: { id: 'Message ID' },
    },
    {
        name: 'gitee_mark_all_messages_read',
        description: 'Mark all private messages as read',
        method: 'PUT',
        path: '/notifications/messages',
        optional: { ids: 'Comma-separated message IDs (empty = all)' },
    },
    {
        name: 'gitee_list_starred_repos',
        description: 'List repositories starred by the authenticated user',
        method: 'GET',
        path: '/user/starred',
        optional: { sort: { description: 'created or updated', enum: ['created', 'updated'] }, direction: { description: 'asc or desc', enum: ['asc', 'desc'] }, page, per_page },
    },
    {
        name: 'gitee_check_starred',
        description: 'Check if the authenticated user has starred a repository',
        method: 'GET',
        path: '/user/starred/{owner}/{repo}',
        required: { owner, repo },
    },
    {
        name: 'gitee_star_repo',
        description: 'Star a repository',
        method: 'PUT',
        path: '/user/starred/{owner}/{repo}',
        required: { owner, repo },
    },
    {
        name: 'gitee_unstar_repo',
        description: 'Unstar a repository',
        method: 'DELETE',
        path: '/user/starred/{owner}/{repo}',
        required: { owner, repo },
    },
    {
        name: 'gitee_list_user_starred',
        description: 'List repositories starred by a user',
        method: 'GET',
        path: '/users/{username}/starred',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_repo_stargazers',
        description: 'List users who starred a repository',
        method: 'GET',
        path: '/repos/{owner}/{repo}/stargazers',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_watched_repos',
        description: 'List repositories watched by the authenticated user',
        method: 'GET',
        path: '/user/subscriptions',
        optional: { sort: { description: 'created or updated', enum: ['created', 'updated'] }, direction: { description: 'asc or desc', enum: ['asc', 'desc'] }, page, per_page },
    },
    {
        name: 'gitee_check_watching',
        description: 'Check if the authenticated user watches a repository',
        method: 'GET',
        path: '/user/subscriptions/{owner}/{repo}',
        required: { owner, repo },
    },
    {
        name: 'gitee_watch_repo',
        description: 'Watch a repository',
        method: 'PUT',
        path: '/user/subscriptions/{owner}/{repo}',
        required: { owner, repo },
    },
    {
        name: 'gitee_unwatch_repo',
        description: 'Unwatch a repository',
        method: 'DELETE',
        path: '/user/subscriptions/{owner}/{repo}',
        required: { owner, repo },
    },
    {
        name: 'gitee_list_user_watched',
        description: 'List repositories watched by a user',
        method: 'GET',
        path: '/users/{username}/subscriptions',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_repo_watchers',
        description: 'List users watching a repository',
        method: 'GET',
        path: '/repos/{owner}/{repo}/subscribers',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_repo_events',
        description: 'List public events for a repository',
        method: 'GET',
        path: '/repos/{owner}/{repo}/events',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_network_events',
        description: 'List public events for a network of repositories',
        method: 'GET',
        path: '/networks/{owner}/{repo}/events',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_org_events',
        description: 'List public events for an organization',
        method: 'GET',
        path: '/orgs/{org}/events',
        required: { org: 'Organization path' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_user_events',
        description: 'List events for a user',
        method: 'GET',
        path: '/users/{username}/events',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_user_public_events',
        description: 'List public events for a user',
        method: 'GET',
        path: '/users/{username}/events/public',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_user_org_events',
        description: 'List events for a user in an organization',
        method: 'GET',
        path: '/users/{username}/events/orgs/{org}',
        required: { username: 'Username', org: 'Organization path' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_received_events',
        description: 'List events received by a user',
        method: 'GET',
        path: '/users/{username}/received_events',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_public_received_events',
        description: 'List public events received by a user',
        method: 'GET',
        path: '/users/{username}/received_events/public',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
];
