import type { ToolDef } from '../types.js';

const page = { description: 'Page number', type: 'number' as const };
const per_page = { description: 'Items per page (max 100)', type: 'number' as const };

export const enterpriseTools: ToolDef[] = [
    {
        name: 'gitee_list_user_enterprises',
        description: 'List enterprises for the authenticated user',
        method: 'GET',
        path: '/user/enterprises',
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_enterprise',
        description: 'Get enterprise information',
        method: 'GET',
        path: '/enterprises/{enterprise}',
        required: { enterprise: 'Enterprise path' },
    },
    {
        name: 'gitee_list_enterprise_members',
        description: 'List enterprise members',
        method: 'GET',
        path: '/enterprises/{enterprise}/members',
        required: { enterprise: 'Enterprise path' },
        optional: {
            role: { description: 'Member role filter', enum: ['all', 'admin', 'member', 'outsourced'] },
            active: { description: 'Filter by active status', type: 'number' },
            page, per_page,
        },
    },
    {
        name: 'gitee_get_enterprise_member',
        description: 'Get enterprise member information',
        method: 'GET',
        path: '/enterprises/{enterprise}/members/{username}',
        required: { enterprise: 'Enterprise path', username: 'Username' },
    },
    {
        name: 'gitee_add_enterprise_member',
        description: 'Add or invite a member to an enterprise',
        method: 'POST',
        path: '/enterprises/{enterprise}/members',
        required: { enterprise: 'Enterprise path', username: 'Username' },
        optional: {
            role: { description: 'Member role', enum: ['admin', 'member', 'outsourced'] },
        },
    },
    {
        name: 'gitee_update_enterprise_member',
        description: 'Update enterprise member permissions',
        method: 'PUT',
        path: '/enterprises/{enterprise}/members/{username}',
        required: { enterprise: 'Enterprise path', username: 'Username' },
        optional: {
            role: { description: 'New role', enum: ['admin', 'member', 'outsourced'] },
            active: { description: 'Active status (0 or 1)', type: 'number' },
        },
    },
    {
        name: 'gitee_remove_enterprise_member',
        description: 'Remove a member from an enterprise',
        method: 'DELETE',
        path: '/enterprises/{enterprise}/members/{username}',
        required: { enterprise: 'Enterprise path', username: 'Username' },
    },
    {
        name: 'gitee_search_enterprise_members',
        description: 'Search enterprise members',
        method: 'GET',
        path: '/enterprises/{enterprise}/members/search',
        required: { enterprise: 'Enterprise path', q: 'Search keyword' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_enterprise_pulls',
        description: 'List enterprise pull requests',
        method: 'GET',
        path: '/enterprise/{enterprise}/pull_requests',
        required: { enterprise: 'Enterprise path' },
        optional: {
            state: { description: 'open, closed, merged, all', enum: ['open', 'closed', 'merged', 'all'] },
            sort: { description: 'Sort: created, updated', enum: ['created', 'updated'] },
            direction: { description: 'asc or desc', enum: ['asc', 'desc'] },
            milestone_number: { description: 'Milestone number', type: 'number' },
            labels: 'Labels filter',
            page, per_page,
        },
    },
    {
        name: 'gitee_list_enterprise_issue_labels',
        description: 'List labels on an enterprise issue',
        method: 'GET',
        path: '/enterprises/{enterprise}/issues/{number}/labels',
        required: { enterprise: 'Enterprise path', number: 'Issue number' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_enterprise_issue_pulls',
        description: 'List pull requests related to an enterprise issue',
        method: 'GET',
        path: '/enterprises/{enterprise}/issues/{number}/pull_requests',
        required: { enterprise: 'Enterprise path', number: 'Issue number' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_user_week_reports',
        description: 'List week reports for a user in an enterprise',
        method: 'GET',
        path: '/enterprises/{enterprise}/users/{username}/week_reports',
        required: { enterprise: 'Enterprise path', username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_week_reports',
        description: 'List all week reports in an enterprise',
        method: 'GET',
        path: '/enterprises/{enterprise}/week_reports',
        required: { enterprise: 'Enterprise path' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_week_report',
        description: 'Get a week report',
        method: 'GET',
        path: '/enterprises/{enterprise}/week_reports/{id}',
        required: { enterprise: 'Enterprise path', id: { description: 'Report ID', type: 'number' } },
    },
    {
        name: 'gitee_create_week_report',
        description: 'Create a week report',
        method: 'POST',
        path: '/enterprises/{enterprise}/week_report',
        required: { enterprise: 'Enterprise path', content: 'Report content' },
        optional: { date_from: 'Start date (YYYY-MM-DD)', date_to: 'End date (YYYY-MM-DD)' },
    },
    {
        name: 'gitee_update_week_report',
        description: 'Update a week report',
        method: 'PATCH',
        path: '/enterprises/{enterprise}/week_report/{id}',
        required: { enterprise: 'Enterprise path', id: { description: 'Report ID', type: 'number' } },
        optional: { content: 'New content' },
    },
    {
        name: 'gitee_list_week_report_comments',
        description: 'List comments on a week report',
        method: 'GET',
        path: '/enterprises/{enterprise}/week_reports/{id}/comments',
        required: { enterprise: 'Enterprise path', id: { description: 'Report ID', type: 'number' } },
        optional: { page, per_page },
    },
    {
        name: 'gitee_create_week_report_comment',
        description: 'Comment on a week report',
        method: 'POST',
        path: '/enterprises/{enterprise}/week_reports/{id}/comment',
        required: { enterprise: 'Enterprise path', id: { description: 'Report ID', type: 'number' }, body: 'Comment body' },
    },
    {
        name: 'gitee_delete_week_report_comment',
        description: 'Delete a week report comment',
        method: 'DELETE',
        path: '/enterprises/{enterprise}/week_reports/{report_id}/comments/{id}',
        required: { enterprise: 'Enterprise path', report_id: { description: 'Report ID', type: 'number' }, id: { description: 'Comment ID', type: 'number' } },
    },
];
