import type { ToolDef } from '../types.js';

const owner = { description: 'Repository owner' };
const repo = { description: 'Repository path name' };
const page = { description: 'Page number', type: 'number' as const };
const per_page = { description: 'Items per page (max 100)', type: 'number' as const };

export const issueTools: ToolDef[] = [
    {
        name: 'gitee_list_issues',
        description: 'List issues for the authenticated user',
        method: 'GET',
        path: '/issues',
        optional: {
            filter: { description: 'assigned, created, mentioned, subscribed, all', enum: ['assigned', 'created', 'mentioned', 'subscribed', 'all'] },
            state: { description: 'open, closed, all', enum: ['open', 'closed', 'all'] },
            labels: 'Comma-separated label names',
            sort: { description: 'created, updated, comments', enum: ['created', 'updated', 'comments'] },
            direction: { description: 'asc or desc', enum: ['asc', 'desc'] },
            since: 'ISO 8601 date',
            page, per_page,
        },
    },
    {
        name: 'gitee_list_user_issues',
        description: 'List issues assigned to the authenticated user',
        method: 'GET',
        path: '/user/issues',
        optional: {
            filter: { description: 'assigned, created, mentioned, subscribed, all', enum: ['assigned', 'created', 'mentioned', 'subscribed', 'all'] },
            state: { description: 'open, closed, all', enum: ['open', 'closed', 'all'] },
            labels: 'Comma-separated label names',
            sort: { description: 'created, updated, comments', enum: ['created', 'updated', 'comments'] },
            direction: { description: 'asc or desc', enum: ['asc', 'desc'] },
            since: 'ISO 8601 date',
            page, per_page,
        },
    },
    {
        name: 'gitee_list_org_issues',
        description: 'List issues in an organization',
        method: 'GET',
        path: '/orgs/{org}/issues',
        required: { org: 'Organization path' },
        optional: {
            filter: { description: 'assigned, created, mentioned, subscribed, all', enum: ['assigned', 'created', 'mentioned', 'subscribed', 'all'] },
            state: { description: 'open, closed, all', enum: ['open', 'closed', 'all'] },
            labels: 'Labels filter',
            sort: { description: 'Sort field', enum: ['created', 'updated', 'comments'] },
            direction: { description: 'asc or desc', enum: ['asc', 'desc'] },
            since: 'ISO 8601 date',
            page, per_page,
        },
    },
    {
        name: 'gitee_list_repo_issues',
        description: 'List issues in a repository',
        method: 'GET',
        path: '/repos/{owner}/{repo}/issues',
        required: { owner, repo },
        optional: {
            state: { description: 'open, closed, all', enum: ['open', 'closed', 'all', 'progressing'] },
            labels: 'Label names',
            sort: { description: 'Sort: created, updated, comments', enum: ['created', 'updated', 'comments'] },
            direction: { description: 'asc or desc', enum: ['asc', 'desc'] },
            since: 'ISO 8601 date',
            only_related_me: { description: 'Only issues related to me', type: 'number' },
            assignee: 'Assignee username',
            creator: 'Creator username',
            program: 'Program ID',
            milestone: 'Milestone number',
            q: 'Search keyword',
            page, per_page,
        },
    },
    {
        name: 'gitee_get_issue',
        description: 'Get a single issue',
        method: 'GET',
        path: '/repos/{owner}/{repo}/issues/{number}',
        required: { owner, repo, number: 'Issue number' },
    },
    {
        name: 'gitee_create_issue',
        description: 'Create an issue',
        method: 'POST',
        path: '/repos/{owner}/issues',
        required: { owner, title: 'Issue title' },
        optional: {
            repo: 'Repository name',
            body: 'Issue body',
            assignee: 'Assignee username',
            milestone: { description: 'Milestone number', type: 'number' },
            labels: 'Comma-separated label names',
            program: 'Program ID',
            security_hole: { description: 'Mark as security hole', type: 'boolean' },
        },
    },
    {
        name: 'gitee_update_issue',
        description: 'Update an issue',
        method: 'PATCH',
        path: '/repos/{owner}/issues/{number}',
        required: { owner, number: 'Issue number' },
        optional: {
            repo: 'Repository name',
            title: 'New title',
            body: 'New body',
            assignee: 'Assignee username',
            milestone: { description: 'Milestone number', type: 'number' },
            labels: 'Labels',
            state: { description: 'open or closed', enum: ['open', 'closed', 'progressing', 'rejected'] },
            security_hole: { description: 'Security hole flag', type: 'boolean' },
        },
    },
    {
        name: 'gitee_get_issue_operation_logs',
        description: 'Get issue operation logs',
        method: 'GET',
        path: '/repos/{owner}/issues/{number}/operate_logs',
        required: { owner, number: 'Issue number' },
        optional: { sort: { description: 'asc or desc', enum: ['asc', 'desc'] } },
    },
    {
        name: 'gitee_list_repo_issue_comments',
        description: 'List all issue comments for a repository',
        method: 'GET',
        path: '/repos/{owner}/{repo}/issues/comments',
        required: { owner, repo },
        optional: { sort: { description: 'created or updated', enum: ['created', 'updated'] }, direction: { description: 'asc or desc', enum: ['asc', 'desc'] }, since: 'ISO 8601 date', page, per_page },
    },
    {
        name: 'gitee_get_issue_comment',
        description: 'Get a single issue comment',
        method: 'GET',
        path: '/repos/{owner}/{repo}/issues/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' } },
    },
    {
        name: 'gitee_list_issue_comments',
        description: 'List comments on an issue',
        method: 'GET',
        path: '/repos/{owner}/{repo}/issues/{number}/comments',
        required: { owner, repo, number: 'Issue number' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_create_issue_comment',
        description: 'Create a comment on an issue',
        method: 'POST',
        path: '/repos/{owner}/{repo}/issues/{number}/comments',
        required: { owner, repo, number: 'Issue number', body: 'Comment body' },
    },
    {
        name: 'gitee_update_issue_comment',
        description: 'Update an issue comment',
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/issues/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' }, body: 'New comment body' },
    },
    {
        name: 'gitee_delete_issue_comment',
        description: 'Delete an issue comment',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/issues/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' } },
    },
    {
        name: 'gitee_list_enterprise_issues',
        description: 'List enterprise issues',
        method: 'GET',
        path: '/enterprises/{enterprise}/issues',
        required: { enterprise: 'Enterprise path' },
        optional: {
            state: { description: 'open, closed, all', enum: ['open', 'closed', 'all'] },
            labels: 'Labels',
            milestone: 'Milestone title',
            assignee: 'Assignee',
            sort: { description: 'Sort field', enum: ['created', 'updated', 'comments'] },
            direction: { description: 'asc or desc', enum: ['asc', 'desc'] },
            since: 'ISO 8601 date',
            page, per_page,
        },
    },
    {
        name: 'gitee_get_enterprise_issue',
        description: 'Get an enterprise issue',
        method: 'GET',
        path: '/enterprises/{enterprise}/issues/{number}',
        required: { enterprise: 'Enterprise path', number: 'Issue number' },
    },
    {
        name: 'gitee_update_enterprise_issue',
        description: 'Update an enterprise issue',
        method: 'PATCH',
        path: '/enterprises/{enterprise}/issues/{number}',
        required: { enterprise: 'Enterprise path', number: 'Issue number' },
        optional: { title: 'Title', body: 'Body', state: { description: 'open or closed', enum: ['open', 'closed'] }, assignee: 'Assignee', milestone: 'Milestone', labels: 'Labels' },
    },
    {
        name: 'gitee_list_enterprise_issue_comments',
        description: 'List comments on an enterprise issue',
        method: 'GET',
        path: '/enterprises/{enterprise}/issues/{number}/comments',
        required: { enterprise: 'Enterprise path', number: 'Issue number' },
        optional: { page, per_page },
    },
];
