import type { ToolDef } from '../types.js';

const owner = { description: 'Repository owner' };
const repo = { description: 'Repository path name' };
const page = { description: 'Page number', type: 'number' as const };
const per_page = { description: 'Items per page (max 100)', type: 'number' as const };

export const pullTools: ToolDef[] = [
    {
        name: 'gitee_list_pulls',
        description: 'List pull requests',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls',
        required: { owner, repo },
        optional: {
            state: { description: 'open, closed, merged, all', enum: ['open', 'closed', 'merged', 'all'] },
            head: 'Filter by head branch (user:branch)',
            base: 'Filter by base branch',
            sort: { description: 'created, updated, popularity, long-running', enum: ['created', 'updated', 'popularity', 'long-running'] },
            direction: { description: 'asc or desc', enum: ['asc', 'desc'] },
            milestone_number: { description: 'Milestone number', type: 'number' },
            labels: 'Labels filter',
            page, per_page,
        },
    },
    {
        name: 'gitee_get_pull',
        description: 'Get a single pull request',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{number}',
        required: { owner, repo, number: 'PR number' },
    },
    {
        name: 'gitee_create_pull',
        description: 'Create a pull request',
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls',
        required: { owner, repo, title: 'PR title', head: 'Head branch (user:branch)', base: 'Base branch' },
        optional: {
            body: 'PR description',
            milestone_number: { description: 'Milestone number', type: 'number' },
            labels: 'Comma-separated label names',
            issue: 'Related issue number',
            assignees: 'Comma-separated reviewer usernames',
            testers: 'Comma-separated tester usernames',
            assignees_number: { description: 'Required reviewer count', type: 'number' },
            testers_number: { description: 'Required tester count', type: 'number' },
            draft: { description: 'Draft PR', type: 'boolean' },
            prune_source_branch: { description: 'Delete source branch after merge', type: 'boolean' },
        },
    },
    {
        name: 'gitee_update_pull',
        description: 'Update a pull request',
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/pulls/{number}',
        required: { owner, repo, number: 'PR number' },
        optional: {
            title: 'New title',
            body: 'New description',
            state: { description: 'open or closed', enum: ['open', 'closed'] },
            milestone_number: { description: 'Milestone', type: 'number' },
            labels: 'Labels',
        },
    },
    {
        name: 'gitee_merge_pull',
        description: 'Merge a pull request',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/pulls/{number}/merge',
        required: { owner, repo, number: 'PR number', merge_method: { description: 'merge, squash, or rebase', enum: ['merge', 'squash', 'rebase'] } },
        optional: { commit_title: 'Merge commit title', commit_message: 'Merge commit message', prune_source_branch: { description: 'Delete source branch', type: 'boolean' } },
    },
    {
        name: 'gitee_check_pull_merged',
        description: 'Check if a pull request has been merged',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{number}/merge',
        required: { owner, repo, number: 'PR number' },
    },
    {
        name: 'gitee_list_pull_commits',
        description: 'List commits on a pull request',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{number}/commits',
        required: { owner, repo, number: 'PR number' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_pull_files',
        description: 'List files changed in a pull request',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{number}/files',
        required: { owner, repo, number: 'PR number' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_pull_issues',
        description: 'List issues linked to a pull request',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{number}/issues',
        required: { owner, repo, number: 'PR number' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_pull_labels',
        description: 'List labels on a pull request',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{number}/labels',
        required: { owner, repo, number: 'PR number' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_create_pull_label',
        description: 'Add labels to a pull request',
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls/{number}/labels',
        required: { owner, repo, number: 'PR number', labels: 'JSON array of label names' },
    },
    {
        name: 'gitee_replace_pull_labels',
        description: 'Replace all labels on a pull request',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/pulls/{number}/labels',
        required: { owner, repo, number: 'PR number', labels: 'JSON array of label names' },
    },
    {
        name: 'gitee_delete_pull_label',
        description: 'Remove a label from a pull request',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/pulls/{number}/labels/{name}',
        required: { owner, repo, number: 'PR number', name: 'Label name' },
    },
    {
        name: 'gitee_get_pull_operation_logs',
        description: 'Get pull request operation logs',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{number}/operate_logs',
        required: { owner, repo, number: 'PR number' },
        optional: { sort: { description: 'asc or desc', enum: ['asc', 'desc'] } },
    },
    {
        name: 'gitee_list_pull_comments',
        description: 'List comments on a pull request',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{number}/comments',
        required: { owner, repo, number: 'PR number' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_pull_comment',
        description: 'Get a pull request comment',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' } },
    },
    {
        name: 'gitee_create_pull_comment',
        description: 'Create a comment on a pull request',
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls/{number}/comments',
        required: { owner, repo, number: 'PR number', body: 'Comment body' },
        optional: { commit_id: 'Commit SHA', path: 'File path', position: { description: 'Line position', type: 'number' } },
    },
    {
        name: 'gitee_update_pull_comment',
        description: 'Update a pull request comment',
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/pulls/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' }, body: 'New comment body' },
    },
    {
        name: 'gitee_delete_pull_comment',
        description: 'Delete a pull request comment',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/pulls/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' } },
    },
    {
        name: 'gitee_handle_pull_review',
        description: 'Approve or request changes on a pull request',
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls/{number}/review',
        required: { owner, repo, number: 'PR number', force: { description: 'Force review (0=no, 1=yes)', type: 'number' } },
    },
    {
        name: 'gitee_assign_pull_reviewers',
        description: 'Assign reviewers to a pull request',
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls/{number}/assignees',
        required: { owner, repo, number: 'PR number', assignees: 'Comma-separated reviewer usernames', assignees_number: { description: 'Required reviewer count', type: 'number' } },
    },
    {
        name: 'gitee_reset_pull_reviewers',
        description: 'Reset reviewer status on a pull request',
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/pulls/{number}/assignees',
        required: { owner, repo, number: 'PR number', assignees: 'Comma-separated reviewer usernames', reset_all: { description: 'Reset all reviewers (0=no, 1=yes)', type: 'number' } },
    },
    {
        name: 'gitee_delete_pull_reviewers',
        description: 'Remove reviewers from a pull request',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/pulls/{number}/assignees',
        required: { owner, repo, number: 'PR number', assignees: 'Comma-separated reviewer usernames' },
    },
    {
        name: 'gitee_assign_pull_testers',
        description: 'Assign testers to a pull request',
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls/{number}/testers',
        required: { owner, repo, number: 'PR number', testers: 'Comma-separated tester usernames', testers_number: { description: 'Required tester count', type: 'number' } },
    },
    {
        name: 'gitee_reset_pull_testers',
        description: 'Reset tester status on a pull request',
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/pulls/{number}/testers',
        required: { owner, repo, number: 'PR number', testers: 'Comma-separated tester usernames', reset_all: { description: 'Reset all testers (0=no, 1=yes)', type: 'number' } },
    },
    {
        name: 'gitee_delete_pull_testers',
        description: 'Remove testers from a pull request',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/pulls/{number}/testers',
        required: { owner, repo, number: 'PR number', testers: 'Comma-separated tester usernames' },
    },
    {
        name: 'gitee_handle_pull_test',
        description: 'Mark test pass/fail on a pull request',
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls/{number}/test',
        required: { owner, repo, number: 'PR number', force: { description: 'Force test result (0=no, 1=yes)', type: 'number' } },
    },
];
