import type { ToolDef } from '../types.js';

const owner = { description: 'Repository owner (user/org/enterprise path)' };
const repo = { description: 'Repository path name' };
const page = { description: 'Page number', type: 'number' as const };
const per_page = { description: 'Items per page (max 100)', type: 'number' as const };

export const repoTools: ToolDef[] = [
    {
        name: 'gitee_get_repo',
        description: 'Get repository information',
        method: 'GET',
        path: '/repos/{owner}/{repo}',
        required: { owner, repo },
    },
    {
        name: 'gitee_update_repo',
        description: 'Update repository settings',
        method: 'PATCH',
        path: '/repos/{owner}/{repo}',
        required: { owner, repo },
        optional: {
            name: 'New repository name',
            description: 'Repository description',
            homepage: 'Repository homepage URL',
            has_issues: { description: 'Enable issues', type: 'boolean' },
            has_wiki: { description: 'Enable wiki', type: 'boolean' },
            can_comment: { description: 'Allow comments', type: 'boolean' },
            auto_init: { description: 'Auto init README', type: 'boolean' },
            gitignore_template: 'Gitignore template name',
            license_template: 'License template',
            private: { description: 'Make private', type: 'boolean' },
            path: 'New repository path',
            default_branch: 'Default branch name',
        },
    },
    {
        name: 'gitee_delete_repo',
        description: 'Delete a repository',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}',
        required: { owner, repo },
    },
    {
        name: 'gitee_list_user_repos',
        description: 'List authenticated user repositories',
        method: 'GET',
        path: '/user/repos',
        optional: {
            visibility: { description: 'Visibility: public, private, all', enum: ['public', 'private', 'all'] },
            affiliation: 'owner, collaborator, organization_member',
            type: { description: 'Filter type: all, owner, personal, member, public, private', enum: ['all', 'owner', 'personal', 'member', 'public', 'private'] },
            sort: { description: 'Sort: created, updated, pushed, full_name', enum: ['created', 'updated', 'pushed', 'full_name'] },
            direction: { description: 'Sort direction: asc, desc', enum: ['asc', 'desc'] },
            q: 'Search keywords',
            page, per_page,
        },
    },
    {
        name: 'gitee_create_user_repo',
        description: 'Create a repository for the authenticated user',
        method: 'POST',
        path: '/user/repos',
        required: { name: 'Repository name' },
        optional: {
            description: 'Repository description',
            homepage: 'Homepage URL',
            private: { description: 'Private repository', type: 'boolean' },
            has_issues: { description: 'Enable issues', type: 'boolean' },
            has_wiki: { description: 'Enable wiki', type: 'boolean' },
            auto_init: { description: 'Auto-initialize with README', type: 'boolean' },
            gitignore_template: 'Gitignore template',
            license_template: 'License template',
        },
    },
    {
        name: 'gitee_list_user_public_repos',
        description: 'List public repositories for a user',
        method: 'GET',
        path: '/users/{username}/repos',
        required: { username: 'Username' },
        optional: { type: { description: 'all, owner, member', enum: ['all', 'owner', 'member'] }, sort: { description: 'Sort by', enum: ['created', 'updated', 'pushed', 'full_name'] }, direction: { description: 'asc or desc', enum: ['asc', 'desc'] }, page, per_page },
    },
    {
        name: 'gitee_list_org_repos',
        description: 'List organization repositories',
        method: 'GET',
        path: '/orgs/{org}/repos',
        required: { org: 'Organization path' },
        optional: { type: { description: 'all, public, private, forks, sources, member', enum: ['all', 'public', 'private', 'forks', 'sources', 'member'] }, page, per_page },
    },
    {
        name: 'gitee_create_org_repo',
        description: 'Create a repository in an organization',
        method: 'POST',
        path: '/orgs/{org}/repos',
        required: { org: 'Organization path', name: 'Repository name' },
        optional: { description: 'Description', private: { description: 'Private', type: 'boolean' }, has_issues: { description: 'Issues enabled', type: 'boolean' }, has_wiki: { description: 'Wiki enabled', type: 'boolean' }, auto_init: { description: 'Auto init', type: 'boolean' }, gitignore_template: 'Gitignore', license_template: 'License' },
    },
    {
        name: 'gitee_list_enterprise_repos',
        description: 'List enterprise repositories',
        method: 'GET',
        path: '/enterprises/{enterprise}/repos',
        required: { enterprise: 'Enterprise path' },
        optional: { type: { description: 'all, public, private, member', enum: ['all', 'public', 'private', 'member'] }, direct: { description: 'Direct repos only', type: 'boolean' }, page, per_page },
    },
    {
        name: 'gitee_create_enterprise_repo',
        description: 'Create a repository in an enterprise',
        method: 'POST',
        path: '/enterprises/{enterprise}/repos',
        required: { enterprise: 'Enterprise path', name: 'Repository name' },
        optional: { description: 'Description', private: { description: 'Private', type: 'boolean' }, has_issues: { description: 'Issues', type: 'boolean' }, has_wiki: { description: 'Wiki', type: 'boolean' }, auto_init: { description: 'Auto init', type: 'boolean' }, gitignore_template: 'Gitignore', license_template: 'License' },
    },
    {
        name: 'gitee_fork_repo',
        description: 'Fork a repository',
        method: 'POST',
        path: '/repos/{owner}/{repo}/forks',
        required: { owner, repo },
        optional: { organization: 'Fork to organization (empty = personal namespace)' },
    },
    {
        name: 'gitee_list_forks',
        description: 'List repository forks',
        method: 'GET',
        path: '/repos/{owner}/{repo}/forks',
        required: { owner, repo },
        optional: { sort: { description: 'Sort: newest, oldest, stargazers', enum: ['newest', 'oldest', 'stargazers'] }, page, per_page },
    },
    {
        name: 'gitee_list_branches',
        description: 'List repository branches',
        method: 'GET',
        path: '/repos/{owner}/{repo}/branches',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_branch',
        description: 'Get a branch',
        method: 'GET',
        path: '/repos/{owner}/{repo}/branches/{branch}',
        required: { owner, repo, branch: 'Branch name' },
    },
    {
        name: 'gitee_create_branch',
        description: 'Create a branch',
        method: 'POST',
        path: '/repos/{owner}/{repo}/branches',
        required: { owner, repo, branch_name: 'New branch name', refs: 'Source branch, tag, or commit SHA' },
    },
    {
        name: 'gitee_protect_branch',
        description: 'Enable branch protection',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/branches/{branch}/protection',
        required: { owner, repo, branch: 'Branch name' },
        optional: { new_name: 'Rename branch' },
    },
    {
        name: 'gitee_unprotect_branch',
        description: 'Disable branch protection',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/branches/{branch}/protection',
        required: { owner, repo, branch: 'Branch name' },
    },
    {
        name: 'gitee_create_branch_protection_rule',
        description: 'Create branch protection rule (wildcard)',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/branches/setting/new',
        required: { owner, repo, wildcard: 'Branch pattern (e.g. feature/*)' },
        optional: { new_wildcard: 'Rename wildcard', pusher_restriction: { description: 'Restrict push: 0=off,1=admin,2=team', type: 'number' }, merger_restriction: { description: 'Restrict merge: 0=off,1=admin,2=team', type: 'number' } },
    },
    {
        name: 'gitee_update_branch_protection_rule',
        description: 'Update branch protection rule',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/branches/{wildcard}/setting',
        required: { owner, repo, wildcard: 'Branch pattern' },
        optional: { new_wildcard: 'New pattern', pusher_restriction: { description: 'Push restriction', type: 'number' }, merger_restriction: { description: 'Merge restriction', type: 'number' } },
    },
    {
        name: 'gitee_delete_branch_protection_rule',
        description: 'Delete branch protection rule',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/branches/{wildcard}/setting',
        required: { owner, repo, wildcard: 'Branch pattern' },
    },
    {
        name: 'gitee_list_commits',
        description: 'List repository commits',
        method: 'GET',
        path: '/repos/{owner}/{repo}/commits',
        required: { owner, repo },
        optional: { sha: 'Branch/tag/commit SHA', path: 'File path filter', author: 'Author username or email', since: 'ISO 8601 start date', until: 'ISO 8601 end date', page, per_page },
    },
    {
        name: 'gitee_get_commit',
        description: 'Get a single commit',
        method: 'GET',
        path: '/repos/{owner}/{repo}/commits/{sha}',
        required: { owner, repo, sha: 'Commit SHA' },
    },
    {
        name: 'gitee_compare_commits',
        description: 'Compare two commits/branches/tags',
        method: 'GET',
        path: '/repos/{owner}/{repo}/compare/{base}...{head}',
        required: { owner, repo, base: 'Base branch/tag/SHA', head: 'Head branch/tag/SHA' },
    },
    {
        name: 'gitee_list_contributors',
        description: 'List repository contributors',
        method: 'GET',
        path: '/repos/{owner}/{repo}/contributors',
        required: { owner, repo },
        optional: { type: { description: 'additions or commits', enum: ['additions', 'commits'] } },
    },
    {
        name: 'gitee_commit_multiple_files',
        description: 'Commit multiple files in one request',
        method: 'POST',
        path: '/repos/{owner}/{repo}/commits',
        required: { owner, repo, branch: 'Target branch', commit_message: 'Commit message', actions: 'JSON array of file actions [{action,file_path,content,encoding,...}]' },
        optional: { author_email: 'Author email', author_name: 'Author name' },
    },
    {
        name: 'gitee_get_file_contents',
        description: 'Get file contents',
        method: 'GET',
        path: '/repos/{owner}/{repo}/contents/{path}',
        required: { owner, repo, path: 'File path' },
        optional: { ref: 'Branch/tag/commit', token: 'Private token (overrides env)' },
    },
    {
        name: 'gitee_create_file',
        description: 'Create a new file',
        method: 'POST',
        path: '/repos/{owner}/{repo}/contents/{path}',
        required: { owner, repo, path: 'File path', message: 'Commit message', content: 'Base64-encoded file content' },
        optional: { branch: 'Branch name (default branch if omitted)', author_email: 'Author email', author_name: 'Author name', committer_email: 'Committer email', committer_name: 'Committer name' },
    },
    {
        name: 'gitee_update_file',
        description: 'Update an existing file',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/contents/{path}',
        required: { owner, repo, path: 'File path', message: 'Commit message', content: 'Base64-encoded new content', sha: 'SHA of the file being replaced' },
        optional: { branch: 'Branch name', author_email: 'Author email', author_name: 'Author name', committer_email: 'Committer email', committer_name: 'Committer name' },
    },
    {
        name: 'gitee_delete_file',
        description: 'Delete a file',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/contents/{path}',
        required: { owner, repo, path: 'File path', message: 'Commit message', sha: 'SHA of the file to delete' },
        optional: { branch: 'Branch name', author_email: 'Author email', author_name: 'Author name', committer_email: 'Committer email', committer_name: 'Committer name' },
    },
    {
        name: 'gitee_get_readme',
        description: 'Get repository README',
        method: 'GET',
        path: '/repos/{owner}/{repo}/readme',
        required: { owner, repo },
        optional: { ref: 'Branch/tag/commit' },
    },
    {
        name: 'gitee_get_raw_file',
        description: 'Get raw file content',
        method: 'GET',
        path: '/repos/{owner}/{repo}/raw/{path}',
        required: { owner, repo, path: 'File path' },
        optional: { ref: 'Branch/tag/commit' },
    },
    {
        name: 'gitee_get_file_blame',
        description: 'Get file blame information',
        method: 'GET',
        path: '/repos/{owner}/{repo}/blame/{path}',
        required: { owner, repo, path: 'File path' },
        optional: { ref: 'Branch/tag/commit' },
    },
    {
        name: 'gitee_list_tags',
        description: 'List repository tags',
        method: 'GET',
        path: '/repos/{owner}/{repo}/tags',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_create_tag',
        description: 'Create a tag',
        method: 'POST',
        path: '/repos/{owner}/{repo}/tags',
        required: { owner, repo, tag_name: 'Tag name', refs: 'Source branch/commit SHA' },
        optional: { tag_message: 'Annotation message (creates annotated tag)', body: 'Release notes for this tag' },
    },
    {
        name: 'gitee_list_collaborators',
        description: 'List repository collaborators',
        method: 'GET',
        path: '/repos/{owner}/{repo}/collaborators',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_check_collaborator',
        description: 'Check if a user is a collaborator',
        method: 'GET',
        path: '/repos/{owner}/{repo}/collaborators/{username}',
        required: { owner, repo, username: 'Username' },
    },
    {
        name: 'gitee_get_collaborator_permission',
        description: 'Get collaborator permission level',
        method: 'GET',
        path: '/repos/{owner}/{repo}/collaborators/{username}/permission',
        required: { owner, repo, username: 'Username' },
    },
    {
        name: 'gitee_add_collaborator',
        description: 'Add or update a collaborator',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/collaborators/{username}',
        required: { owner, repo, username: 'Username' },
        optional: { permission: { description: 'Permission: pull, push, admin', enum: ['pull', 'push', 'admin'] } },
    },
    {
        name: 'gitee_remove_collaborator',
        description: 'Remove a collaborator',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/collaborators/{username}',
        required: { owner, repo, username: 'Username' },
    },
    {
        name: 'gitee_list_deploy_keys',
        description: 'List deploy keys',
        method: 'GET',
        path: '/repos/{owner}/{repo}/keys',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_deploy_key',
        description: 'Get a deploy key',
        method: 'GET',
        path: '/repos/{owner}/{repo}/keys/{id}',
        required: { owner, repo, id: { description: 'Key ID', type: 'number' } },
    },
    {
        name: 'gitee_add_deploy_key',
        description: 'Add a deploy key',
        method: 'POST',
        path: '/repos/{owner}/{repo}/keys',
        required: { owner, repo, key: 'Public SSH key', title: 'Key title' },
        optional: { read_only: { description: 'Read-only key', type: 'boolean' } },
    },
    {
        name: 'gitee_delete_deploy_key',
        description: 'Delete a deploy key',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/keys/{id}',
        required: { owner, repo, id: { description: 'Key ID', type: 'number' } },
    },
    {
        name: 'gitee_enable_deploy_key',
        description: 'Enable a deploy key',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/keys/enable/{id}',
        required: { owner, repo, id: { description: 'Key ID', type: 'number' } },
    },
    {
        name: 'gitee_disable_deploy_key',
        description: 'Disable a deploy key',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/keys/enable/{id}',
        required: { owner, repo, id: { description: 'Key ID', type: 'number' } },
    },
    {
        name: 'gitee_list_available_keys',
        description: 'List available (user) deploy keys for the repo',
        method: 'GET',
        path: '/repos/{owner}/{repo}/keys/available',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_releases',
        description: 'List releases',
        method: 'GET',
        path: '/repos/{owner}/{repo}/releases',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_release',
        description: 'Get a release by ID',
        method: 'GET',
        path: '/repos/{owner}/{repo}/releases/{id}',
        required: { owner, repo, id: { description: 'Release ID', type: 'number' } },
    },
    {
        name: 'gitee_get_latest_release',
        description: 'Get the latest release',
        method: 'GET',
        path: '/repos/{owner}/{repo}/releases/latest',
        required: { owner, repo },
    },
    {
        name: 'gitee_get_release_by_tag',
        description: 'Get a release by tag name',
        method: 'GET',
        path: '/repos/{owner}/{repo}/releases/tags/{tag}',
        required: { owner, repo, tag: 'Tag name' },
    },
    {
        name: 'gitee_create_release',
        description: 'Create a release',
        method: 'POST',
        path: '/repos/{owner}/{repo}/releases',
        required: { owner, repo, tag_name: 'Tag name', name: 'Release name' },
        optional: { body: 'Release description', prerelease: { description: 'Mark as pre-release', type: 'boolean' }, target_commitish: 'Target branch or SHA' },
    },
    {
        name: 'gitee_update_release',
        description: 'Update a release',
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/releases/{id}',
        required: { owner, repo, id: { description: 'Release ID', type: 'number' } },
        optional: { tag_name: 'Tag name', name: 'Release name', body: 'Description', prerelease: { description: 'Pre-release', type: 'boolean' }, target_commitish: 'Target branch/SHA' },
    },
    {
        name: 'gitee_delete_release',
        description: 'Delete a release',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/releases/{id}',
        required: { owner, repo, id: { description: 'Release ID', type: 'number' } },
    },
    {
        name: 'gitee_list_release_attachments',
        description: 'List release attachments',
        method: 'GET',
        path: '/repos/{owner}/{repo}/releases/{release_id}/attach_files',
        required: { owner, repo, release_id: { description: 'Release ID', type: 'number' } },
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_release_attachment',
        description: 'Get a release attachment',
        method: 'GET',
        path: '/repos/{owner}/{repo}/releases/{release_id}/attach_files/{attach_file_id}',
        required: { owner, repo, release_id: { description: 'Release ID', type: 'number' }, attach_file_id: { description: 'Attachment ID', type: 'number' } },
    },
    {
        name: 'gitee_delete_release_attachment',
        description: 'Delete a release attachment',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/releases/{release_id}/attach_files/{attach_file_id}',
        required: { owner, repo, release_id: { description: 'Release ID', type: 'number' }, attach_file_id: { description: 'Attachment ID', type: 'number' } },
    },
    {
        name: 'gitee_list_repo_commit_comments',
        description: 'List all commit comments for a repository',
        method: 'GET',
        path: '/repos/{owner}/{repo}/comments',
        required: { owner, repo },
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_commit_comment',
        description: 'Get a commit comment',
        method: 'GET',
        path: '/repos/{owner}/{repo}/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' } },
    },
    {
        name: 'gitee_update_commit_comment',
        description: 'Update a commit comment',
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' }, body: 'New comment body' },
    },
    {
        name: 'gitee_delete_commit_comment',
        description: 'Delete a commit comment',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/comments/{id}',
        required: { owner, repo, id: { description: 'Comment ID', type: 'number' } },
    },
    {
        name: 'gitee_list_commit_comments',
        description: 'List comments for a specific commit',
        method: 'GET',
        path: '/repos/{owner}/{repo}/commits/{ref}/comments',
        required: { owner, repo, ref: 'Commit SHA or ref' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_create_commit_comment',
        description: 'Create a comment on a commit',
        method: 'POST',
        path: '/repos/{owner}/{repo}/commits/{sha}/comments',
        required: { owner, repo, sha: 'Commit SHA', body: 'Comment body' },
        optional: { path: 'File path', position: { description: 'Line position', type: 'number' }, line: { description: 'Line number', type: 'number' } },
    },
    {
        name: 'gitee_get_push_config',
        description: 'Get repository push rules configuration',
        method: 'GET',
        path: '/repos/{owner}/{repo}/push_config',
        required: { owner, repo },
    },
    {
        name: 'gitee_update_push_config',
        description: 'Update repository push rules',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/push_config',
        required: { owner, repo },
        optional: {
            restrict_push_own_commit: { description: 'Restrict push to own commits', type: 'boolean' },
            restrict_author_email_suffix: { description: 'Restrict author email suffix', type: 'boolean' },
            author_email_suffix: 'Allowed email suffix',
            restrict_commit_message: { description: 'Restrict commit message format', type: 'boolean' },
            commit_message_regex: 'Commit message regex pattern',
            except_manager: { description: 'Exempt managers', type: 'boolean' },
        },
    },
    {
        name: 'gitee_get_pages',
        description: 'Get Gitee Pages configuration',
        method: 'GET',
        path: '/repos/{owner}/{repo}/pages',
        required: { owner, repo },
    },
    {
        name: 'gitee_update_pages',
        description: 'Update Gitee Pages settings',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/pages',
        required: { owner, repo },
        optional: { https: { description: 'Force HTTPS', type: 'boolean' }, domain: 'Custom domain' },
    },
    {
        name: 'gitee_build_pages',
        description: 'Trigger a Gitee Pages build',
        method: 'POST',
        path: '/repos/{owner}/{repo}/pages/builds',
        required: { owner, repo },
    },
    {
        name: 'gitee_get_traffic_data',
        description: 'Get repository traffic statistics',
        method: 'POST',
        path: '/repos/{owner}/{repo}/traffic-data',
        required: { owner, repo, start_day: 'Start date (YYYY-MM-DD)', end_day: 'End date (YYYY-MM-DD)' },
    },
    {
        name: 'gitee_update_reviewer_settings',
        description: 'Update code review settings',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/reviewer',
        required: { owner, repo },
        optional: {
            assignees_number: { description: 'Required reviewers count', type: 'number' },
            testers_number: { description: 'Required testers count', type: 'number' },
            assignees: 'Comma-separated reviewer usernames',
            testers: 'Comma-separated tester usernames',
        },
    },
    {
        name: 'gitee_clear_repo',
        description: 'Clear all content from a repository (destructive!)',
        method: 'PUT',
        path: '/repos/{owner}/{repo}/clear',
        required: { owner, repo },
    },
    {
        name: 'gitee_get_repo_license',
        description: 'Get repository license information',
        method: 'GET',
        path: '/repos/{owner}/{repo}/license',
        required: { owner, repo },
    },
    {
        name: 'gitee_enable_gitee_go',
        description: 'Enable Gitee Go for the repository',
        method: 'POST',
        path: '/repos/{owner}/{repo}/open',
        required: { owner, repo },
    },
    {
        name: 'gitee_get_baidu_statistic_key',
        description: 'Get Baidu Analytics key for repository',
        method: 'GET',
        path: '/repos/{owner}/{repo}/baidu_statistic_key',
        required: { owner, repo },
    },
    {
        name: 'gitee_set_baidu_statistic_key',
        description: 'Set Baidu Analytics key for repository',
        method: 'POST',
        path: '/repos/{owner}/{repo}/baidu_statistic_key',
        required: { owner, repo, id: 'Baidu Analytics site ID' },
    },
    {
        name: 'gitee_delete_baidu_statistic_key',
        description: 'Delete Baidu Analytics key',
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/baidu_statistic_key',
        required: { owner, repo },
    },
];
