import type { ToolDef } from '../types.js';

const page = { description: 'Page number', type: 'number' as const };
const per_page = { description: 'Items per page (max 100)', type: 'number' as const };

export const userTools: ToolDef[] = [
    {
        name: 'gitee_get_current_user',
        description: 'Get the authenticated user profile',
        method: 'GET',
        path: '/user',
    },
    {
        name: 'gitee_update_current_user',
        description: 'Update the authenticated user profile',
        method: 'PATCH',
        path: '/user',
        optional: {
            name: 'Display name',
            blog: 'Blog URL',
            weibo: 'Weibo URL',
            bio: 'Biography',
        },
    },
    {
        name: 'gitee_get_user',
        description: 'Get a user by username',
        method: 'GET',
        path: '/users/{username}',
        required: { username: 'Username' },
    },
    {
        name: 'gitee_list_followers',
        description: 'List followers of the authenticated user',
        method: 'GET',
        path: '/user/followers',
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_following',
        description: 'List users the authenticated user is following',
        method: 'GET',
        path: '/user/following',
        optional: { page, per_page },
    },
    {
        name: 'gitee_check_following',
        description: 'Check if the authenticated user follows someone',
        method: 'GET',
        path: '/user/following/{username}',
        required: { username: 'Username to check' },
    },
    {
        name: 'gitee_follow_user',
        description: 'Follow a user',
        method: 'PUT',
        path: '/user/following/{username}',
        required: { username: 'Username to follow' },
    },
    {
        name: 'gitee_unfollow_user',
        description: 'Unfollow a user',
        method: 'DELETE',
        path: '/user/following/{username}',
        required: { username: 'Username to unfollow' },
    },
    {
        name: 'gitee_list_user_followers',
        description: 'List followers of a specific user',
        method: 'GET',
        path: '/users/{username}/followers',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_user_following',
        description: 'List users a specific user is following',
        method: 'GET',
        path: '/users/{username}/following',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_check_user_following',
        description: 'Check if a user follows another user',
        method: 'GET',
        path: '/users/{username}/following/{target_user}',
        required: { username: 'Username', target_user: 'Target username' },
    },
    {
        name: 'gitee_list_user_keys',
        description: 'List public SSH keys for a user',
        method: 'GET',
        path: '/users/{username}/keys',
        required: { username: 'Username' },
        optional: { page, per_page },
    },
    {
        name: 'gitee_list_my_keys',
        description: 'List public SSH keys for the authenticated user',
        method: 'GET',
        path: '/user/keys',
        optional: { page, per_page },
    },
    {
        name: 'gitee_get_key',
        description: 'Get a public SSH key',
        method: 'GET',
        path: '/user/keys/{id}',
        required: { id: { description: 'Key ID', type: 'number' } },
    },
    {
        name: 'gitee_add_key',
        description: 'Add a public SSH key',
        method: 'POST',
        path: '/user/keys',
        required: { key: 'Public SSH key content', title: 'Key title' },
    },
    {
        name: 'gitee_delete_key',
        description: 'Delete a public SSH key',
        method: 'DELETE',
        path: '/user/keys/{id}',
        required: { id: { description: 'Key ID', type: 'number' } },
    },
    {
        name: 'gitee_get_namespace',
        description: 'Get a namespace by path',
        method: 'GET',
        path: '/user/namespace',
        required: { path: 'Namespace path' },
    },
    {
        name: 'gitee_list_namespaces',
        description: 'List all namespaces accessible to the user',
        method: 'GET',
        path: '/user/namespaces',
        optional: { mode: { description: 'Filter mode: project, intl', enum: ['project', 'intl'] } },
    },
    {
        name: 'gitee_get_emails',
        description: 'List email addresses for the authenticated user',
        method: 'GET',
        path: '/emails',
    },
];
